# Generated by Django 4.2.1 on 2023-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.CharField(help_text='Nhập tên diễn viên', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(help_text='Nhập tên đạo diễn', max_length=255),
        ),
    ]
