# Generated by Django 4.2.1 on 2023-06-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_movie_actor_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='fk_food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.food'),
        ),
        migrations.DeleteModel(
            name='MyList',
        ),
    ]
