# Generated by Django 4.2.1 on 2023-06-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_myrating_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrating',
            name='id_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.movie'),
        ),
    ]
