# Generated by Django 4.2.1 on 2023-07-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_myrating_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myrating',
            options={'ordering': ['rating']},
        ),
    ]
