# Generated by Django 4.2.1 on 2023-07-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_myrating_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrating',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.username'),
        ),
    ]
